# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 09:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200)),
                ('check_date', models.DateTimeField(verbose_name='check date')),
            ],
        ),
        migrations.CreateModel(
            name='PrList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=200, unique=True, verbose_name='Название списка')),
                ('creation_date', models.DateTimeField(verbose_name='Дата создания')),
                ('modify_date', models.DateTimeField(verbose_name='Дата обновления')),
                ('list_type', models.IntegerField(default=0, verbose_name='Тип списка: 1-блеклист, 2-вайтлист')),
                ('bid', models.FloatField(default=0, verbose_name='Бид')),
                ('list_id_on_src', models.IntegerField(default=None, verbose_name='ID в источнике')),
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Country', verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(verbose_name='Код')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('config', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name_plural': 'Провайдеры',
                'verbose_name': 'Провайдер',
            },
        ),
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_id', models.IntegerField(default=0)),
                ('domain', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Domain')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Provider')),
            ],
        ),
        migrations.AddField(
            model_name='prlist',
            name='pubs',
            field=models.ManyToManyField(to='api.Pub', verbose_name='Пабы'),
        ),
        migrations.AddField(
            model_name='prlist',
            name='root_list',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.PrList', verbose_name='Родительский список'),
        ),
        migrations.AddField(
            model_name='prlist',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Provider', verbose_name='Источник'),
        ),
    ]
