# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prlist',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='prlist',
            name='list_type',
            field=models.SmallIntegerField(choices=[(1, '1-блеклист'), (2, '2-вайтлист')], default=0, verbose_name='Тип списка'),
        ),
    ]
